"""Move connected

Revision ID: e4363dc98c83
Revises: 3cd888acf752
Create Date: 2018-05-02 19:37:38.047449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4363dc98c83'
down_revision = '3cd888acf752'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objects', 'connected')
    op.add_column('players', sa.Column('connected', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'connected')
    op.add_column('objects', sa.Column('connected', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###
